### ISSUE TITLE
configuring a target pace

### ISSUE THREAD

**Issue by autonome** [neverstopstudio/targetpace#1]
the user must be input a target pace.

requirements:
- the user needs to be able to set it manually
- the user needs change to a new target pace easily
- the user can select a previously configured pace

in the main ui, swiping left takes the user to the pace setting screen.

the pace setting screen:
- swiping up/down will increase/decrease the target pace
- there are visual cues indicating this (eg arrows)
- swiping repeatedly left will scroll through previously configured pace targets, touching one will make it the target pace

**Comment by MBenz12** [comment]
implemented in this [commit](https://github.com/neverstopstudio/bignum/commit/c502a54b47822506722a27670c90adab1bc4c195)
