### ISSUE TITLE
integrate into existing workouts

### ISSUE THREAD

**Issue by autonome** [neverstopstudio/targetpace#6]
eventually maybe we integrate into RunRecorder, but for now we can piggyback on existing workouts.

user flow:
- starts a run using other app
- opens TargetPace
- visually sees there's a workout in progress
- configures target pace
- goes running

if no workout in progress, or is not a running workout, the app should throw a big screen up preventing use.

**Comment by MBenz12** [comment]
I tried to implement this way, but failed.
in an app can't access other app's health data.
I think we should directly integrate into RunRecoder now.
if you have any ui/ux patten, please share it

**Comment by MBenz12** [comment]
what about using navigation link icons?
![image](https://github.com/neverstopstudio/targetpace/assets/101111807/72ee48ac-8c9a-444e-b956-518a1bfbee28)
![image](https://github.com/neverstopstudio/targetpace/assets/101111807/f43d4bc4-4c1b-4731-8d03-0b456a356ec9)

**Comment by MBenz12** [comment]
please check runrecoder app, I integrated target pace into it.
https://github.com/neverstopstudio/runrecorder/pull/17
