### ISSUE TITLE
eye-free usage

### ISSUE THREAD

**Issue by autonome** [neverstopstudio/targetpace#7]
after configuring a pace, the app should be usable without looking at it.

this is accomplished by using vibration patterns.

let's start with these, and can tweak based on testing and user feedback:

- target pace is achieved: single 3s vibration
- running too fast: 3 short vibrations, 500ms apart
- running too slow: 3 short vibrations, 1s apart

**Comment by MBenz12** [comment]
could you check vibration effect in [runrecoder](https://github.com/neverstopstudio/runrecorder/commit/b665b50f828d098fd123d9bc34ed1ed1b660e599)?
